#!/usr/bin/env python3
"""Convert ref/assets PNGs into a GBA 15-bit sprite header (src/gd_assets.h).

Each pixel is a uint16 BGR555 value; bit15 (0x8000) marks an opaque pixel,
0x0000 marks transparent (matches draw_sprite() in graphics.c). Sprite sheets
are emitted as flat row-major arrays; the engine/fender/helmet sheets are laid
out 6 frames per row exactly as the reference (col = frame%6, row = frame/6).

Run from the repo root:  python3 tools/convert_assets.py
"""
import os
from PIL import Image

ASSETS = os.path.join(os.path.dirname(__file__), "..", "ref", "assets")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "gd_assets.h")


def to555(r, g, b, a):
    if a < 128:
        return 0x0000
    return 0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def load(name):
    im = Image.open(os.path.join(ASSETS, name)).convert("RGBA")
    return im, im.width, im.height


def emit_array(f, cname, pixels, w, h):
    f.write(f"static const color_t {cname}[{w * h}] = {{\n")
    for y in range(h):
        row = pixels[y * w:(y + 1) * w]
        f.write("  " + ",".join("0x%04x" % p for p in row) + ",\n")
    f.write("};\n")


def flatten(im):
    px = im.load()
    out = []
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            out.append(to555(r, g, b, a))
    return out


def emit_image(f, cname, name):
    im, w, h = load(name)
    f.write(f"#define {cname.upper()}_W {w}\n#define {cname.upper()}_H {h}\n")
    emit_array(f, cname, flatten(im), w, h)


def emit_subrect(f, cname, im, ox, oy, w, h):
    px = im.load()
    out = []
    for y in range(oy, oy + h):
        for x in range(ox, ox + w):
            r, g, b, a = px[x, y]
            out.append(to555(r, g, b, a))
    f.write(f"#define {cname.upper()}_W {w}\n#define {cname.upper()}_H {h}\n")
    emit_array(f, cname, out, w, h)


def main():
    with open(OUT, "w") as f:
        f.write("#ifndef GD_ASSETS_H\n#define GD_ASSETS_H\n")
        f.write("// Auto-generated by tools/convert_assets.py from ref/assets. Do not edit.\n")
        f.write('#include "gba.h"\n\n')

        # Full single images
        emit_image(f, "splash_img", "splash.png")
        emit_image(f, "logo_img", "logo.png")

        # 6-column rotation sheets (frame W/H = sheet / 6)
        for cname, fname in (("engine_sheet", "engine.png"),
                             ("fender_sheet", "fender.png"),
                             ("helmet_sheet", "helmet.png")):
            im, w, h = load(fname)
            f.write(f"#define {cname.upper()}_W {w}\n#define {cname.upper()}_H {h}\n")
            f.write(f"#define {cname.upper()}_FW {w // 6}\n#define {cname.upper()}_FH {h // 6}\n")
            emit_array(f, cname, flatten(im), w, h)

        # Wheel tires from sprites.png atlas (sprite 0 = thin, 1 = thick), both 15x15.
        spr = Image.open(os.path.join(ASSETS, "sprites.png")).convert("RGBA")
        emit_subrect(f, "wheel_thin", spr, 0, 10, 15, 15)
        emit_subrect(f, "wheel_thick", spr, 0, 25, 15, 15)

        f.write("#endif // GD_ASSETS_H\n")
    print("wrote", os.path.relpath(OUT))


if __name__ == "__main__":
    main()
