#!/usr/bin/env python3
"""Convert assets/ PNGs into a GBA 15-bit sprite header (src/gd_assets.h).

Each pixel is a uint16 BGR555 value; bit15 (0x8000) marks an opaque pixel,
0x0000 marks transparent (matches draw_sprite() in graphics.c). Sprite sheets
are emitted as flat row-major arrays; the engine/fender/helmet sheets are laid
out 6 frames per row exactly as the reference (col = frame%6, row = frame/6).

Run from the repo root:  python3 tools/convert_assets.py
"""
import colorsys
import os
from PIL import Image

ASSETS = os.path.join(os.path.dirname(__file__), "..", "assets")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "gd_assets.h")

# Predefined customization palette, shared by the helmet, the rider suit, and
# the bike accent. Each entry recolors a part by *setting* the hue of its
# saturated pixels to this value while preserving each pixel's saturation and
# brightness, so the artist's shading survives and near-grey trim is untouched
# (see recolor_pixel). The hues are chosen so the defaults reproduce the
# original art exactly: index 1 (yellow) for the helmet, 4 (blue) for the suit,
# 0 (red) for the bike. Keep this in sync with the swatch table in main.c and
# the default indices in save.c. Hue is in degrees.
PALETTE = [
    ("RED",      0),
    ("YELLOW",  54),
    ("GREEN",  120),
    ("CYAN",   188),
    ("BLUE",   214),
    ("MAGENTA", 305),
]
# Pixels below this saturation are treated as neutral trim/highlights and left
# as-is, so only the themed region (suit/shell/accent) is recolored.
SAT_THRESHOLD = 0.20


def to555(r, g, b, a):
    if a < 128:
        return 0x0000
    return 0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def recolor_pixel(r, g, b, a, hue_deg):
    if a < 128:
        return (r, g, b, a)
    h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
    if s < SAT_THRESHOLD:
        return (r, g, b, a)  # neutral trim/highlight: leave untouched
    nr, ng, nb = colorsys.hsv_to_rgb(hue_deg / 360.0, s, v)
    return (int(nr * 255 + 0.5), int(ng * 255 + 0.5), int(nb * 255 + 0.5), a)


def load(name):
    im = Image.open(os.path.join(ASSETS, name)).convert("RGBA")
    return im, im.width, im.height


def emit_array(f, cname, pixels, w, h):
    f.write(f"static const color_t {cname}[{w * h}] = {{\n")
    for y in range(h):
        row = pixels[y * w:(y + 1) * w]
        f.write("  " + ",".join("0x%04x" % p for p in row) + ",\n")
    f.write("};\n")


def flatten(im):
    px = im.load()
    out = []
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            out.append(to555(r, g, b, a))
    return out


def emit_image(f, cname, name):
    im, w, h = load(name)
    f.write(f"#define {cname.upper()}_W {w}\n#define {cname.upper()}_H {h}\n")
    emit_array(f, cname, flatten(im), w, h)


def emit_color_family(f, array_name, define_prefix, fname, fh_div):
    """Emit a [CUSTOM_COLOR_COUNT][w*h] array of hue-recolored sheet variants,
    one per PALETTE entry. The _W/_H/_FW/_FH defines use define_prefix and match
    the single-sheet layout (col = frame%6, row = frame/fh_div)."""
    im, w, h = load(fname)
    f.write(f"#define {define_prefix}_W {w}\n#define {define_prefix}_H {h}\n")
    f.write(f"#define {define_prefix}_FW {w // 6}\n#define {define_prefix}_FH {h // fh_div}\n")
    px = im.load()
    f.write(f"static const color_t {array_name}[CUSTOM_COLOR_COUNT][{w * h}] = {{\n")
    for _, hue in PALETTE:
        f.write("{\n")
        for y in range(h):
            row = []
            for x in range(w):
                r, g, b, a = recolor_pixel(*px[x, y], hue)
                row.append(to555(r, g, b, a))
            f.write("  " + ",".join("0x%04x" % p for p in row) + ",\n")
        f.write("},\n")
    f.write("};\n")


def emit_subrect(f, cname, im, ox, oy, w, h):
    px = im.load()
    out = []
    for y in range(oy, oy + h):
        for x in range(ox, ox + w):
            r, g, b, a = px[x, y]
            out.append(to555(r, g, b, a))
    f.write(f"#define {cname.upper()}_W {w}\n#define {cname.upper()}_H {h}\n")
    emit_array(f, cname, out, w, h)


def main():
    with open(OUT, "w") as f:
        f.write("#ifndef GD_ASSETS_H\n#define GD_ASSETS_H\n")
        f.write("// Auto-generated by tools/convert_assets.py from assets/. Do not edit.\n")
        f.write('#include "gba.h"\n\n')

        # Number of selectable colors per customizable part (helmet/suit/bike).
        f.write(f"#define CUSTOM_COLOR_COUNT {len(PALETTE)}\n\n")

        # Full single images
        emit_image(f, "splash_img", "splash.png")

        # Customizable 6-column rotation sheets, one tinted variant per palette
        # color. Bike = engine + fender accent; helmet = its own shell color.
        emit_color_family(f, "engine_sheets", "ENGINE_SHEET", "engine.png", 6)
        emit_color_family(f, "fender_sheets", "FENDER_SHEET", "fender.png", 6)
        emit_color_family(f, "helmet_sheets", "HELMET_SHEET", "helmet.png", 6)

        # Customizable rider limb sheets (the suit color): 6 columns x 3 rows
        # (16 of 18 frames used over [0,pi), matching the reference
        # renderBodyPart -> calcSpriteNo(angle, 0, pi, 16, false)).
        emit_color_family(f, "arm_sheets", "ARM_SHEET", "bluearm.png", 3)
        emit_color_family(f, "leg_sheets", "LEG_SHEET", "blueleg.png", 3)
        emit_color_family(f, "body_sheets", "BODY_SHEET", "bluebody.png", 3)

        # Wheel tires from sprites.png atlas (sprite 0 = thin, 1 = thick), both 15x15.
        spr = Image.open(os.path.join(ASSETS, "sprites.png")).convert("RGBA")
        emit_subrect(f, "wheel_thin", spr, 0, 10, 15, 15)
        emit_subrect(f, "wheel_thick", spr, 0, 25, 15, 15)

        f.write("#endif // GD_ASSETS_H\n")
    print("wrote", os.path.relpath(OUT))


if __name__ == "__main__":
    main()
